### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by EinDev** [traycold/xposed-yota-eink-notif#1]
I'm unable to load the module.
I installed the APK from ADB, but it doesn't create any file.
No logcat messages about that.
May it be a problem, that i'm having no SD-card?

Thanks for your help and for creating this project - i would really like to fork it to make a GUI. 
(with your permission)

**Comment by traycold** [comment]
hi, sorry I don't have the yotaphone since some time, so not able to help anymore or continue development. So I will be glad if you would take in charge the module.

**Comment by EinDev** [comment]
Hey, Can you remember how you activated the Module? I don't Understand how it should get activated.Am 08.04.2018 22:43 schrieb traycold <notifications@github.com>:hi, sorry I don't have the yotaphone since some time, so not able to help anymore or continue development. So I will be glad if you would take in charge the module.

**Comment by traycold** [comment]
to be honest not sure 100% but I remember I did nothing special to activate module, just standard procedure of Xposed Module, i.e. install APK manually, then activate it in the Xposed app, restart the app.

**Comment by EinDev** [comment]
Didn't know about any xposed-app, will try to find it as soon as i'm home. ThanksAm 09.04.2018 9:08 vorm. schrieb traycold <notifications@github.com>:to be honest not sure 100% but I remember I did nothing special to activate module, just standard procedure of Xposed Module, i.e. install APK manually, then activate it in the Xposed app, restart the app.
